// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("E5SCm6xZkiclk63r");
export default defineConfig({
  generate: {
    plan({ snaplet, pipe }) {
      return pipe(
        snaplet.users({ count: 10 }),
        snaplet.todos({ count: 20 }, { autoConnect: true })
      );
    },
  },
  select: {
    $default: false,
    auth: true,
    public: true,
  },
  transform: {
    auth: {
      users({ row }) {
        if (row.role === "<email over here>") {
          return row;
        }

        return {
          role: copycat.fullName(row.role, {
            limit: 255,
          }),
          email: copycat.email(row.email, {
            limit: 255,
          }),
          phone: copycat.phoneNumber(row.phone),
        };
      },
    },
    public: {
      todos({ row }) {
        return {
          title: copycat.fullName(row.title),
        };
      },
    },
  },
});
