// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("E5SCm6xZkiclk63r");
export default defineConfig({
  generate: {
    plan({ snaplet }) {
      return snaplet.todos({
        count: 20,
        // data: {
        //   users: {
        //     data: {
        //       email: ({ seed }) =>
        //         copycat.email(seed, {
        //           domain: "gmail.com",
        //         }),
        //     },
        //   },
        // },
      });
    },
  },
  select: {
    storage: false,
    supabase_functions: false,
  },
  transform: {
    auth: {
      users({ row }) {
        if (row.role === "<email over here>") {
          return row;
        }

        return {
          role: copycat.fullName(row.role, {
            limit: 255,
          }),
          email: copycat.email(row.email, {
            limit: 255,
          }),
          phone: copycat.phoneNumber(row.phone),
        };
      },
    },
    pgsodium: {
      key({ row }) {
        return {
          name: copycat.fullName(row.name),
          user_data: copycat.username(row.user_data),
        };
      },
    },
    vault: {
      secrets({ row }) {
        return {
          name: copycat.fullName(row.name),
          secret: copycat.streetAddress(row.secret),
          nonce: copycat.hex(row.nonce),
        };
      },
    },
    public: {
      todos({ row }) {
        return {
          title: copycat.fullName(row.title),
        };
      },
    },
  },
});
