// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("E5SCm6xZkiclk63r");
export default defineConfig({
  generate: {
    run: async (snaplet) => {
      await snaplet.$pipe([
        // create 10 users
        snaplet.users((x) =>
          x(10, (index) => {
            return {
              // all the users have `acme.org` as their email domain
              email: `user${index}@acme.org`,
            };
          })
        ),
        // create 20 todos, connect them to one of the users
        snaplet.todos((x) => x(20), { autoConnect: true }),
      ]);
    },
  },
  select: {
    $default: false,
    auth: true,
    public: true,
  },
  transform: {
    auth: {
      users({ row }) {
        if (row.role === "<email over here>") {
          return row;
        }

        return {
          role: copycat.fullName(row.role, {
            limit: 255,
          }),
          email: copycat.email(row.email, {
            limit: 255,
          }),
          phone: copycat.phoneNumber(row.phone),
        };
      },
    },
    public: {
      todos({ row }) {
        return {
          title: copycat.fullName(row.title),
        };
      },
    },
  },
});
